services:
  db:
    image: postgres:15.1
    container_name: db-vigia
    restart: always
    env_file:
      - ../.env
    environment:
      - POSTGRES_PORT="${PGPORT}"
      - POSTGRES_USER="${PGUSER}"
      - POSTGRES_PASSWORD="${PGPASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  pgdata: