name: CD Desarrollo VigiA - Backend
on:
  push:
    paths-ignore:
      - ".github/**"
      - "*.md"
    branches: [develop]
  pull_request:
    types: [closed]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16 
      - name: Instalar Serverlesss
        run: npm install serverless -g
      - name: Instalar dependencias
        run: npm install
      - name: 'Crear archivo .env'
        run: |
          touch .env
          echo NODE_ENV="dev" > .env
          echo TWITTER_API_KEY=${{ secrets.DEV_TWITTER_API_KEY}} > .env
          echo TWITTER_API_KEY_SECRET=${{ secrets.DEV_TWITTER_API_KEY_SECRET }} > .env
          echo TWITTER_ACCESS_TOKEN=${{ secrets.DEV_TWITTER_ACCESS_TOKEN }} > .env
          echo TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.DEV_TWITTER_ACCESS_TOKEN_SECRET }} > .env
          echo FRONTEND_URL=${{ secrets.DEV_FRONTEND_URL }} > .env
          echo PGDATABASE=${{ secrets.DEV_PGDATABASE }} > .env
          echo PGHOST=${{ secrets.DEV_PGHOST }} > .env
          echo PGPASSWORD=${{ secrets.DEV_PGPASSWORD }} > .env
          echo PGPORT=${{ secrets.DEV_PGPORT }} > .env
          echo PGUSER=${{ secrets.DEV_PGUSER }} > .env
          echo REQUEST_TOKEN_API_DNCP=${{ secrets.REQUEST_TOKEN_API_DNCP}} > .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} > .env
          echo EMAIL_FROM=${{ secrets.EMAIL_FROM }} > .env
          echo EMAIL_PASS=${{ secrets.EMAIL_PASS }} > .env
          cat .env
      - name: Deployando con Serverless
        run: sls deploy --stage dev --region sa-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}